#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  leftClaw,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rightClaw,      sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port4,           leftForklift,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port5,           rightForklift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Supporting Files
#include <Functions.c>
#include <Tasks.c>

//Variables
int maxSpeed = 128;



void pre_auton() {
  bStopTasksBetweenModes = true;
}



task autonomous() {
	startTask(forwardBackward); //Either
	//startTask(forwardBackwardCubeLeftStart); //Blue
	//startTask(forwardBackwardCubeRightStart); //Red
}



/*
	Joysticks:
		1	[None]
		2	Right Drive Control
		3	Left Drive Control
		4	[None]
	Buttons:
		5U && 5D	Lift Encoder Reset <<<We either need to remove this or get a partner controller for the claw.>>>
		6U && 6D	Variable Drive Speed Control
			6U -> 128 maxSpeed
			6D -> 32 maxSpeed
		7U && 7L && 7R && 7D	Forklift Control
			7U -> Raise Forklift
			7L && 7R -> Stop Forklift
			7D -> Lower Forklift
		8U && 8L && 8R && 8D	Lift Control
			8U -> Extend Lift
			8L && 8R -> Stop Lift
			8D -> Retract Lift
*/
task usercontrol() {

	nMotorEncoder[lift] = 0;

	while(true) {

		if(vexRT[Btn5U] && vexRT[Btn5D]) {
			nMotorEncoder[lift] = 0;
		}
		if(vexRT[Btn6U]) {
			maxSpeed = 128; //Change the maximum speed to 128 (maximum value)
		} else if(vexRT[Btn6D]) {
			maxSpeed = 32; //Change the maximum speed to 32 (1/4 of the maximum value)
		}

		motor[leftDrive] = vexRT[Ch3] * (maxSpeed / 128.0);
		motor[rightDrive] = vexRT[Ch2] * (maxSpeed / 128.0);
		//motor[leftDrive] = abs(vexRT[Ch3]) >= 4 ? vexRT[Ch3] * (maxSpeed / 128.0) : 0; //left side speed is determined by the left joystick
		//motor[rightDrive] = abs(vexRT[Ch2]) >= 4 ? vexRT[Ch2] * (maxSpeed / 128.0) : 0; //right side speed is determined by the right joystick

		 if(vexRT[Btn7L] || vexRT[Btn7R]) { //If buttons 7L or 7R are pressed
			motor[leftForklift] = 0;
			motor[rightForklift] = 0;
		} else if(vexRT[Btn7U]) { //If button 7U is pressed
			motor[leftForklift] = 128;
			motor[rightForklift] = 128;
		} else if(vexRT[Btn7D]) { //If button 7D is pressed
			motor[leftForklift] = -32;
			motor[rightForklift] = -32;
		}

		if(vexRT[Btn8U] && !(abs(nMotorEncoder[lift]) >= 17.5 / (0.5 * PI) * 627.2)) {
			motor[lift] = 128;
		} else if(vexRT[Btn8D]) {
			motor[lift] = -128;
		}
		if(vexRT[Btn8L] || vexRT[Btn8R] || abs(nMotorEncoder[lift]) >= 17.5 / (0.5 * PI) * 627.2) {
			motor[lift] = 0;
		}

	}
}
