#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  rightButton,    sensorTouch)
#pragma config(Sensor, dgtl2,  leftButton,     sensorTouch)
#pragma config(Sensor, dgtl3,  jumper,         sensorDigitalIn)
#pragma config(Sensor, dgtl11, claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl12, led,            sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           leftForklift,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           rightForklift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           forklift3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDrive,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <data.c>

int enableClaw = 1;
int leftJoystick = 0;
int rightJoystick = 0;
int button5U = 0;
int button6U = 0;
int button6D = 0;

task main() {

	clearTimer(T1);

	//Loop through this 100 times a second for n number of seconds
	for(int i = 0; i < 100 * 10; i++) {

		leftJoystick = data[i][0];
		rightJoystick = data[i][1];
		button5U = data[i][2];
		button6U = data[i][3];
		button6D = data[i][4];

		motor[leftDrive] = leftJoystick;
		motor[rightDrive] = rightJoystick;

		if(!button6U && !button6D) {
			motor[leftForklift] = 0;
			motor[rightForklift] = 0;
			motor[forklift3] = 0;
		} if(button6U) {
			motor[leftForklift] = 127;
			motor[rightForklift] = 127;
			motor[forklift3] = 127;
		} else if(button6D) {
		 	motor[leftForklift] = -128;
			motor[rightForklift] = -128;
			motor[forklift3] = -128;
		}

		if(button5U && enableClaw) {
			SensorValue[claw] = !SensorValue[claw];
			enableClaw = 0;
			clearTimer(T1);
		}

		if(time1(T1) > 250) {
			enableClaw = 1;
		}

		delay(10);

	}

}
